apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "reddit-digest-agent.fullname" . }}
  labels:
    {{- include "reddit-digest-agent.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.extraEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
