apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "reddit-digest-agent.fullname" . }}
  labels:
    {{- include "reddit-digest-agent.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
